/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khanzacetakantrianloket;

import fungsi.akses;
import bridging.PCarePeserta;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Timer;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.awt.Desktop;
import java.net.URI;


/**
 *
 * @author windiartonugroho
 */
public class frmUtama extends javax.swing.JFrame {
    private final Connection koneksi=koneksiDB.condb();
    private final validasi Valid=new validasi();
    private final sekuel Sequel=new sekuel();
    private PreparedStatement ps;
    private ResultSet rs;
    /**
     * Creates new form frmUtama
     */
    public frmUtama() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        BtnCetak1 = new widget.Button();
        BtnCetak2 = new widget.Button();
        BtnCetak3 = new widget.Button();
        BtnCetak4 = new widget.Button();
        BtnCetak5 = new widget.Button();
        BtnCetak6 = new widget.Button();
        BtnCetak7 = new widget.Button();
        BtnCetak8 = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ANJUNGAN PASIEN MANDIRI");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        internalFrame1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCetak1.setForeground(new java.awt.Color(15, 81, 137));
        BtnCetak1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/tombolatm.png"))); // NOI18N
        BtnCetak1.setText("POLI UMUM");
        BtnCetak1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        BtnCetak1.setGlassColor(new java.awt.Color(255, 255, 255));
        BtnCetak1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnCetak1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnCetak1.setIconTextGap(25);
        BtnCetak1.setMaximumSize(new java.awt.Dimension(429, 81));
        BtnCetak1.setMinimumSize(new java.awt.Dimension(429, 81));
        BtnCetak1.setPreferredSize(new java.awt.Dimension(158, 125));
        BtnCetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetak1ActionPerformed(evt);
            }
        });
        internalFrame1.add(BtnCetak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 350, 100));

        BtnCetak2.setForeground(new java.awt.Color(15, 81, 137));
        BtnCetak2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/tombolatm.png"))); // NOI18N
        BtnCetak2.setText("POLI GIGI");
        BtnCetak2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        BtnCetak2.setGlassColor(new java.awt.Color(255, 255, 255));
        BtnCetak2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnCetak2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnCetak2.setIconTextGap(25);
        BtnCetak2.setMaximumSize(new java.awt.Dimension(429, 81));
        BtnCetak2.setMinimumSize(new java.awt.Dimension(429, 81));
        BtnCetak2.setPreferredSize(new java.awt.Dimension(158, 125));
        BtnCetak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetak2ActionPerformed(evt);
            }
        });
        internalFrame1.add(BtnCetak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 420, 100));

        BtnCetak3.setForeground(new java.awt.Color(15, 81, 137));
        BtnCetak3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/tombolatm - kanan.png"))); // NOI18N
        BtnCetak3.setText("AKTIFASI SATU SEHAT");
        BtnCetak3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        BtnCetak3.setGlassColor(new java.awt.Color(255, 255, 255));
        BtnCetak3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BtnCetak3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnCetak3.setIconTextGap(50);
        BtnCetak3.setMaximumSize(new java.awt.Dimension(429, 81));
        BtnCetak3.setMinimumSize(new java.awt.Dimension(429, 81));
        BtnCetak3.setPreferredSize(new java.awt.Dimension(158, 125));
        BtnCetak3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetak3ActionPerformed(evt);
            }
        });
        internalFrame1.add(BtnCetak3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 350, 100));

        BtnCetak4.setBorder(null);
        BtnCetak4.setForeground(new java.awt.Color(255, 255, 255));
        BtnCetak4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Untitled design(1).png"))); // NOI18N
        BtnCetak4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        BtnCetak4.setGlassColor(new java.awt.Color(255, 255, 255));
        BtnCetak4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnCetak4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnCetak4.setIconTextGap(25);
        BtnCetak4.setMaximumSize(new java.awt.Dimension(429, 81));
        BtnCetak4.setMinimumSize(new java.awt.Dimension(429, 81));
        BtnCetak4.setPreferredSize(new java.awt.Dimension(158, 125));
        BtnCetak4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetak4ActionPerformed(evt);
            }
        });
        internalFrame1.add(BtnCetak4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 910, 180));

        BtnCetak5.setForeground(new java.awt.Color(15, 81, 137));
        BtnCetak5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/tombolatm - kanan.png"))); // NOI18N
        BtnCetak5.setText("POLI KB");
        BtnCetak5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        BtnCetak5.setGlassColor(new java.awt.Color(255, 255, 255));
        BtnCetak5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BtnCetak5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnCetak5.setIconTextGap(25);
        BtnCetak5.setMaximumSize(new java.awt.Dimension(429, 81));
        BtnCetak5.setMinimumSize(new java.awt.Dimension(429, 81));
        BtnCetak5.setPreferredSize(new java.awt.Dimension(158, 125));
        BtnCetak5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetak5ActionPerformed(evt);
            }
        });
        internalFrame1.add(BtnCetak5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 350, 100));

        BtnCetak6.setForeground(new java.awt.Color(15, 81, 137));
        BtnCetak6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/tombolatm - kanan.png"))); // NOI18N
        BtnCetak6.setText("POLI KIA");
        BtnCetak6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        BtnCetak6.setGlassColor(new java.awt.Color(255, 255, 255));
        BtnCetak6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BtnCetak6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnCetak6.setIconTextGap(50);
        BtnCetak6.setMaximumSize(new java.awt.Dimension(429, 81));
        BtnCetak6.setMinimumSize(new java.awt.Dimension(429, 81));
        BtnCetak6.setPreferredSize(new java.awt.Dimension(158, 125));
        BtnCetak6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetak6ActionPerformed(evt);
            }
        });
        internalFrame1.add(BtnCetak6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 350, 100));

        BtnCetak7.setForeground(new java.awt.Color(15, 81, 137));
        BtnCetak7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/tombolatm.png"))); // NOI18N
        BtnCetak7.setText("CETAK NOMOR ANTRIAN");
        BtnCetak7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        BtnCetak7.setGlassColor(new java.awt.Color(255, 255, 255));
        BtnCetak7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnCetak7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnCetak7.setIconTextGap(25);
        BtnCetak7.setMaximumSize(new java.awt.Dimension(429, 81));
        BtnCetak7.setMinimumSize(new java.awt.Dimension(429, 81));
        BtnCetak7.setPreferredSize(new java.awt.Dimension(158, 125));
        BtnCetak7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetak7ActionPerformed(evt);
            }
        });
        internalFrame1.add(BtnCetak7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 320, 100));

        BtnCetak8.setForeground(new java.awt.Color(15, 81, 137));
        BtnCetak8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/tombolatm.png"))); // NOI18N
        BtnCetak8.setText("CEK KEPESERTAAN");
        BtnCetak8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        BtnCetak8.setGlassColor(new java.awt.Color(255, 255, 255));
        BtnCetak8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnCetak8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnCetak8.setIconTextGap(25);
        BtnCetak8.setMaximumSize(new java.awt.Dimension(429, 81));
        BtnCetak8.setMinimumSize(new java.awt.Dimension(429, 81));
        BtnCetak8.setPreferredSize(new java.awt.Dimension(158, 125));
        BtnCetak8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetak8ActionPerformed(evt);
            }
        });
        internalFrame1.add(BtnCetak8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 350, 100));

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void BtnCetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetak1ActionPerformed
        RMPasien pilih = new  RMPasien(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_BtnCetak1ActionPerformed

    private void BtnCetak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetak2ActionPerformed
        RMPasien pilih = new  RMPasien(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_BtnCetak2ActionPerformed

    private void BtnCetak3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetak3ActionPerformed
            try {
            String baseUrl = "http://192.168.18.162/"; // URL dasar
            String endpoint = "kyc-library-php/"; // Endpoint yang akan ditambahkan

            // Gabungkan URL dengan benar
            String fullUrl = baseUrl + endpoint;

            // Membuka URL di browser default
            Desktop desktop = Desktop.getDesktop();
            URI uri = new URI(fullUrl);
            desktop.browse(uri); // Membuka URL di browser
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_BtnCetak3ActionPerformed

    private void BtnCetak4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetak4ActionPerformed
        Antrian pilih = new  Antrian();
        pilih.autonomer();
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_BtnCetak4ActionPerformed

    private void BtnCetak5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetak5ActionPerformed
        RMPasien pilih = new  RMPasien(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_BtnCetak5ActionPerformed

    private void BtnCetak6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetak6ActionPerformed
        RMPasien pilih = new  RMPasien(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_BtnCetak6ActionPerformed

    private void BtnCetak7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetak7ActionPerformed
        Antrian pilih = new  Antrian();
        pilih.autonomer();
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_BtnCetak7ActionPerformed

    private void BtnCetak8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetak8ActionPerformed
        PCarePeserta pilih = new  PCarePeserta();
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_BtnCetak8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCetak1;
    private widget.Button BtnCetak2;
    private widget.Button BtnCetak3;
    private widget.Button BtnCetak4;
    private widget.Button BtnCetak5;
    private widget.Button BtnCetak6;
    private widget.Button BtnCetak7;
    private widget.Button BtnCetak8;
    private widget.InternalFrame internalFrame1;
    // End of variables declaration//GEN-END:variables


}
